llm:
  provider: "openai"
  model: "gpt-4-turbo-preview"
  temperature: 0.7
  max_tokens: 4096
  api_key: "${OPENAI_API_KEY}"

embedding:
  type: "sqlite"  # Use SQLite for local development
  connection:
    path: "data/embeddings.db"
  dimension: 1536
  collection_names:
    confluence: "confluence_embeddings"
    databricks: "databricks_schema_embeddings"

database:
  type: "sqlite"
  path: "data/conversations.db"

agents:
  supervisor:
    name: "Supervisor"
    description: "Coordinates between specialized agents"
    group_chat:
      max_round: 10
      roles:
        - name: "Coordinator"
          description: "Analyzes questions and coordinates responses"
        - name: "Synthesizer"
          description: "Combines responses from multiple sources"

  confluence:
    name: "Confluence"
    description: "Searches and analyzes Confluence content"
    connection:
      url: "${CONFLUENCE_URL}"
      username: "${CONFLUENCE_USERNAME}"
      password: "${CONFLUENCE_PASSWORD}"
      space_key: "${CONFLUENCE_SPACE_KEY}"
      embedding_batch_size: 100
    group_chat:
      max_round: 8
      roles:
        - name: "ContentExpert"
          description: "Analyzes and understands content"
        - name: "SearchExpert"
          description: "Handles search and retrieval"
        - name: "TextAnalyzer"
          description: "Analyzes user intent"

  databricks:
    name: "Databricks"
    description: "Queries and analyzes Databricks data"
    connection:
      host: "${DATABRICKS_HOST}"
      port: 443
      http_path: "${DATABRICKS_HTTP_PATH}"
      access_token: "${DATABRICKS_ACCESS_TOKEN}"
      schema_cache_ttl: 3600
    group_chat:
      max_round: 8
      roles:
        - name: "SQLExpert"
          description: "Generates and optimizes SQL queries"
        - name: "SchemaExpert"
          description: "Analyzes database schema"
        - name: "QueryValidator"
          description: "Validates query correctness"

  graphql:
    name: "GraphQL"
    description: "Queries and analyzes GraphQL APIs"
    connection:
      endpoint: "${GRAPHQL_ENDPOINT}"
      headers:
        Authorization: "Bearer ${GRAPHQL_TOKEN}"
      schema_cache_ttl: 3600
    group_chat:
      max_round: 8
      roles:
        - name: "SchemaExpert"
          description: "Analyzes GraphQL schema"
        - name: "QueryExpert"
          description: "Generates GraphQL queries"

memory:
  type: "sqlite"
  path: "data/conversations.db"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

api:
  host: "localhost"
  port: 8000
  debug: true
  cors_origins: ["*"]

monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30 