llm:
  provider: "gemini"
  model: "gemini-pro"
  temperature: 0.7
  max_tokens: 4096

embedding:
  store: "memory"
  dimension: 1536

database:
  type: "sqlite"
  path: "data/conversations.db"

agents:
  supervisor:
    name: "Supervisor"
    description: "Coordinates between specialized agents"
    max_iterations: 10
    timeout: 300
    group_chat:
      max_round: 10
      agents:
        - name: "Coordinator"
          role: "Analyze questions and coordinate between agents"
        - name: "Synthesizer"
          role: "Combine responses from multiple agents"

  confluence:
    name: "ConfluenceExpert"
    description: "Expert in retrieving information from Confluence"
    max_iterations: 5
    timeout: 120
    embedding_batch_size: 100

  databricks:
    name: "DatabricksExpert"
    description: "Expert in Databricks SQL and system tables"
    max_iterations: 5
    timeout: 120
    group_chat:
      max_round: 10
      agents:
        - name: "SQLExpert"
          role: "Generate and optimize SQL queries"
        - name: "SchemaExpert"
          role: "Analyze database schemas"
        - name: "QueryValidator"
          role: "Validate and improve queries"

  graphql:
    name: "GraphQLExpert"
    description: "Expert in GraphQL queries and schema"
    max_iterations: 5
    timeout: 120
    schema_cache_ttl: 3600

memory:
  type: "sqlite"
  path: "data/conversations.db"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

api:
  host: "0.0.0.0"
  port: 8000
  debug: true
  workers: 2 